# -*- coding: utf-8 -*-
"""ATM machine project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16t3PLRf6QrSWP3MTChIzsVMUffPX6tYT
"""

s='''
1.credit
2.Debit
3.mini statement
4.exit
'''
amount=1000
while True:
    print('welcome to the ATM machine')
    print('Beaware from your OTP')
    account_number=int(input('enter the account number'))
    password=int(input('enter the 4 digits password'))
    option=input('enter your option')
    if option==1:
        print(amount+credit_amount)

    elif option==2:
         print(amount-debit_amount)
    elif option==3:
        print(amount)
    else:
        print(exit)