# -*- coding: utf-8 -*-
"""Learnerns management system project 1  .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sy478fCt-KQiEiCESieT7XXF3KxlI75Q

> Problem statement
Goal --> Create a program that allows a user to store multiple students names and marks .The program must automatically calculate a grade (A ,B,C or Fail) based on the marks abd allow the user to view all stored records until they choose to exit .

>
"""

students={}
while True:
  print("1.Add student")
  print("2.view students")
  print("3.Exit")
  choice=int(input('Enter your choice'))
  if choice==1:
    name=input('Enter student name')
    marks=int(input('Enter student marks'))
    if marks>=90:
      grade="A"
    elif marks>=80:
      grade="B"
    elif marks>=70:
      grade="C"
    else:
      grade="Fail"
    students[name]={"marks":marks,"grade":"grade"}
  elif choice==2:
    for key,value in students.items():
      print(key, value)
  elif choice==3:
    print('Existing program')
    break
  else:
    print("Invaild choice")













