# -*- coding: utf-8 -*-
"""Number guessing game 2 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sy478fCt-KQiEiCESieT7XXF3KxlI75Q

Problem statement-- You choose a lower number and a upper number and computer can randomly picks one number in that range and you get 7 chances to guess the number and after every guess the number toohigh --> Guess a smaller number and Too low --> Guess a bigger number , if you get correctly --> you win and If you have 7 chances to win .
"""

import random
print("welcome to number guessing game")
print("You have 7 chances to win")
low=int(input("enter the Lower bound"))
high=int(input("enter the upper bound"))
secret=random.randint(low,high)
chances=7
print("low and high .Try to guess it")
for attempt in range(1,chances+1):
    guess=int(input("enter your guess"))
    if guess==secret:
        print("you win")
        break
    elif guess>secret:
        print("Too high")
    else:
        print("low number ")











